export interface WmDateTimeProps {
  styles?: React.CSSProperties;
  name?: string;
  placeholder?: string;
  hint?: string;
  showampmbuttons?: boolean;
  tabindex?: number;
  shortcutkey?: string;
  datavalue?: string | Date | null;
  datepattern?: string;
  hourstep?: number;
  minutestep?: number;
  outputformat?: string;
  required?: boolean;
  mindate?: string | Date;
  maxdate?: string | Date;
  excludedays?: string;
  excludedates?: string | string[] | Date[];
  showweeks?: boolean;
  showbuttonbar?: boolean;
  autofocus?: boolean;
  readonly?: boolean;
  show?: boolean;
  disabled?: boolean;
  selectfromothermonth?: boolean;
  todaybutton?: boolean;
  clearbutton?: boolean;
  todaybuttonlabel?: string;
  clearbuttonlabel?: string;
  showcustompicker?: boolean;
  adaptiveposition?: boolean;
  showdropdownon?: string;
  dataentrymode?: string;
  width?: string | number;
  arialabel?: string;
  className?: string;
  onDateChange?: (date: Date | null) => void;
  isValidDate?: (date: Date) => boolean;
  getDateObj?: (value: any) => Date;
  minDateMaxDateValidationOnInput?: (date: Date) => boolean;
  formatValidation?: (date: Date, dateString: string) => boolean;
  updatePrevDatavalue?: (date: Date | null) => void;
  updateBoundVariable?: (date: Date | null) => void;
  handleKeyDown?: (event: React.KeyboardEvent) => void;
  onChange?: (event: React.SyntheticEvent, widget: any, newValue: any, oldValue: any) => void;
  onClick?: (event: React.MouseEvent, widget: any) => void;
  onFocus?: (event: React.FocusEvent, widget: any) => void;
  onBlur?: (event: React.FocusEvent, widget: any) => void;
  onMouseEnter?: (event: React.MouseEvent, widget: any) => void;
  onMouseLeave?: (event: React.MouseEvent, widget: any) => void;
  onBeforeload?: (event: React.SyntheticEvent, widget: any) => void;
  listener: Record<string, any>;
  [key: string]: any;
  floatinglabel?: string;
}
