import { includes, toLower } from "lodash-es";
//Radioset Constants
interface DatasetItem {
  key: string | number;
  value: any;
  label: string;
  selected?: boolean;
}

export const ALL_FIELDS = "All Fields";

export const defaultItems: DatasetItem[] = [
  { key: "Option 1", value: "Option 1", label: "Option 1", selected: false },
  { key: "Option 2", value: "Option 2", label: "Option 2", selected: false },
  { key: "Option 3", value: "Option 3", label: "Option 3", selected: false },
];

export const progressBarConstants = {
  DEFAULT_TYPE: "default",
  DEFAULT_CAPTION_PLACEMENT: "hidden",
  DEFAULT_MIN_VALUE: 0,
  DEFAULT_MAX_VALUE: 100,
  DEFAULT_CLASS: "progress app-progress",
  DEFAULT_HEIGHT: "0.25em",
  DECIMAL_COUNT_MAP: {
    "9": 0,
    "9.9": 1,
    "9.99": 2,
    "9.999": 3,
    "9%": 0,
    "9.9%": 1,
    "9.99%": 2,
    "9.999%": 3,
  },
} as const;

export const currencyConstants = {
  DEFAULT_CLS: "input-group app-currency",
  appDefaultCurrency: "USD",
  CURRENCY_INFO: {
    USD: {
      symbol: "$",
      name: "US Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "USD",
      name_plural: "US dollars",
    },
    CAD: {
      symbol: "CA$",
      name: "Canadian Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "CAD",
      name_plural: "Canadian dollars",
    },
    EUR: {
      symbol: "\u20ac",
      name: "Euro",
      symbol_native: "\u20ac",
      decimal_digits: 2,
      rounding: 0,
      code: "EUR",
      name_plural: "euros",
    },
    AED: {
      symbol: "AED",
      name: "United Arab Emirates Dirham",
      symbol_native: "\u062f.\u0625.\u200f",
      decimal_digits: 2,
      rounding: 0,
      code: "AED",
      name_plural: "UAE dirhams",
    },
    AFN: {
      symbol: "Af",
      name: "Afghan Afghani",
      symbol_native: "\u060b",
      decimal_digits: 0,
      rounding: 0,
      code: "AFN",
      name_plural: "Afghan Afghanis",
    },
    ALL: {
      symbol: "ALL",
      name: "Albanian Lek",
      symbol_native: "Lek",
      decimal_digits: 0,
      rounding: 0,
      code: "ALL",
      name_plural: "Albanian lek\xeb",
    },
    AMD: {
      symbol: "AMD",
      name: "Armenian Dram",
      symbol_native: "\u0564\u0580.",
      decimal_digits: 0,
      rounding: 0,
      code: "AMD",
      name_plural: "Armenian drams",
    },
    ARS: {
      symbol: "AR$",
      name: "Argentine Peso",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "ARS",
      name_plural: "Argentine pesos",
    },
    AUD: {
      symbol: "AU$",
      name: "Australian Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "AUD",
      name_plural: "Australian dollars",
    },
    AZN: {
      symbol: "man.",
      name: "Azerbaijani Manat",
      symbol_native: "\u043c\u0430\u043d.",
      decimal_digits: 2,
      rounding: 0,
      code: "AZN",
      name_plural: "Azerbaijani manats",
    },
    BAM: {
      symbol: "KM",
      name: "Bosnia-Herzegovina Convertible Mark",
      symbol_native: "KM",
      decimal_digits: 2,
      rounding: 0,
      code: "BAM",
      name_plural: "Bosnia-Herzegovina convertible marks",
    },
    BDT: {
      symbol: "Tk",
      name: "Bangladeshi Taka",
      symbol_native: "\u09f3",
      decimal_digits: 2,
      rounding: 0,
      code: "BDT",
      name_plural: "Bangladeshi takas",
    },
    BGN: {
      symbol: "BGN",
      name: "Bulgarian Lev",
      symbol_native: "\u043b\u0432.",
      decimal_digits: 2,
      rounding: 0,
      code: "BGN",
      name_plural: "Bulgarian leva",
    },
    BHD: {
      symbol: "BD",
      name: "Bahraini Dinar",
      symbol_native: "\u062f.\u0628.\u200f",
      decimal_digits: 3,
      rounding: 0,
      code: "BHD",
      name_plural: "Bahraini dinars",
    },
    BIF: {
      symbol: "FBu",
      name: "Burundian Franc",
      symbol_native: "FBu",
      decimal_digits: 0,
      rounding: 0,
      code: "BIF",
      name_plural: "Burundian francs",
    },
    BND: {
      symbol: "BN$",
      name: "Brunei Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "BND",
      name_plural: "Brunei dollars",
    },
    BOB: {
      symbol: "Bs",
      name: "Bolivian Boliviano",
      symbol_native: "Bs",
      decimal_digits: 2,
      rounding: 0,
      code: "BOB",
      name_plural: "Bolivian bolivianos",
    },
    BRL: {
      symbol: "R$",
      name: "Brazilian Real",
      symbol_native: "R$",
      decimal_digits: 2,
      rounding: 0,
      code: "BRL",
      name_plural: "Brazilian reals",
    },
    BWP: {
      symbol: "BWP",
      name: "Botswanan Pula",
      symbol_native: "P",
      decimal_digits: 2,
      rounding: 0,
      code: "BWP",
      name_plural: "Botswanan pulas",
    },
    BYR: {
      symbol: "BYR",
      name: "Belarusian Ruble",
      symbol_native: "BYR",
      decimal_digits: 0,
      rounding: 0,
      code: "BYR",
      name_plural: "Belarusian rubles",
    },
    BZD: {
      symbol: "BZ$",
      name: "Belize Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "BZD",
      name_plural: "Belize dollars",
    },
    CDF: {
      symbol: "CDF",
      name: "Congolese Franc",
      symbol_native: "FrCD",
      decimal_digits: 2,
      rounding: 0,
      code: "CDF",
      name_plural: "Congolese francs",
    },
    CHF: {
      symbol: "CHF",
      name: "Swiss Franc",
      symbol_native: "CHF",
      decimal_digits: 2,
      rounding: 0.05,
      code: "CHF",
      name_plural: "Swiss francs",
    },
    CLP: {
      symbol: "CL$",
      name: "Chilean Peso",
      symbol_native: "$",
      decimal_digits: 0,
      rounding: 0,
      code: "CLP",
      name_plural: "Chilean pesos",
    },
    CNY: {
      symbol: "CN\xa5",
      name: "Chinese Yuan",
      symbol_native: "CN\xa5",
      decimal_digits: 2,
      rounding: 0,
      code: "CNY",
      name_plural: "Chinese yuan",
    },
    COP: {
      symbol: "CO$",
      name: "Colombian Peso",
      symbol_native: "$",
      decimal_digits: 0,
      rounding: 0,
      code: "COP",
      name_plural: "Colombian pesos",
    },
    CRC: {
      symbol: "\u20a1",
      name: "Costa Rican Col\xf3n",
      symbol_native: "\u20a1",
      decimal_digits: 0,
      rounding: 0,
      code: "CRC",
      name_plural: "Costa Rican col\xf3ns",
    },
    CVE: {
      symbol: "CV$",
      name: "Cape Verdean Escudo",
      symbol_native: "CV$",
      decimal_digits: 2,
      rounding: 0,
      code: "CVE",
      name_plural: "Cape Verdean escudos",
    },
    CZK: {
      symbol: "K\u010d",
      name: "Czech Republic Koruna",
      symbol_native: "K\u010d",
      decimal_digits: 2,
      rounding: 0,
      code: "CZK",
      name_plural: "Czech Republic korunas",
    },
    DJF: {
      symbol: "Fdj",
      name: "Djiboutian Franc",
      symbol_native: "Fdj",
      decimal_digits: 0,
      rounding: 0,
      code: "DJF",
      name_plural: "Djiboutian francs",
    },
    DKK: {
      symbol: "Dkr",
      name: "Danish Krone",
      symbol_native: "kr",
      decimal_digits: 2,
      rounding: 0,
      code: "DKK",
      name_plural: "Danish kroner",
    },
    DOP: {
      symbol: "RD$",
      name: "Dominican Peso",
      symbol_native: "RD$",
      decimal_digits: 2,
      rounding: 0,
      code: "DOP",
      name_plural: "Dominican pesos",
    },
    DZD: {
      symbol: "DA",
      name: "Algerian Dinar",
      symbol_native: "\u062f.\u062c.\u200f",
      decimal_digits: 2,
      rounding: 0,
      code: "DZD",
      name_plural: "Algerian dinars",
    },
    EEK: {
      symbol: "Ekr",
      name: "Estonian Kroon",
      symbol_native: "kr",
      decimal_digits: 2,
      rounding: 0,
      code: "EEK",
      name_plural: "Estonian kroons",
    },
    EGP: {
      symbol: "EGP",
      name: "Egyptian Pound",
      symbol_native: "\u062c.\u0645.\u200f",
      decimal_digits: 2,
      rounding: 0,
      code: "EGP",
      name_plural: "Egyptian pounds",
    },
    ERN: {
      symbol: "Nfk",
      name: "Eritrean Nakfa",
      symbol_native: "Nfk",
      decimal_digits: 2,
      rounding: 0,
      code: "ERN",
      name_plural: "Eritrean nakfas",
    },
    ETB: {
      symbol: "Br",
      name: "Ethiopian Birr",
      symbol_native: "Br",
      decimal_digits: 2,
      rounding: 0,
      code: "ETB",
      name_plural: "Ethiopian birrs",
    },
    GBP: {
      symbol: "\xa3",
      name: "British Pound Sterling",
      symbol_native: "\xa3",
      decimal_digits: 2,
      rounding: 0,
      code: "GBP",
      name_plural: "British pounds sterling",
    },
    GEL: {
      symbol: "GEL",
      name: "Georgian Lari",
      symbol_native: "GEL",
      decimal_digits: 2,
      rounding: 0,
      code: "GEL",
      name_plural: "Georgian laris",
    },
    GHS: {
      symbol: "GH\u20b5",
      name: "Ghanaian Cedi",
      symbol_native: "GH\u20b5",
      decimal_digits: 2,
      rounding: 0,
      code: "GHS",
      name_plural: "Ghanaian cedis",
    },
    GNF: {
      symbol: "FG",
      name: "Guinean Franc",
      symbol_native: "FG",
      decimal_digits: 0,
      rounding: 0,
      code: "GNF",
      name_plural: "Guinean francs",
    },
    GTQ: {
      symbol: "GTQ",
      name: "Guatemalan Quetzal",
      symbol_native: "Q",
      decimal_digits: 2,
      rounding: 0,
      code: "GTQ",
      name_plural: "Guatemalan quetzals",
    },
    HKD: {
      symbol: "HK$",
      name: "Hong Kong Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "HKD",
      name_plural: "Hong Kong dollars",
    },
    HNL: {
      symbol: "HNL",
      name: "Honduran Lempira",
      symbol_native: "L",
      decimal_digits: 2,
      rounding: 0,
      code: "HNL",
      name_plural: "Honduran lempiras",
    },
    HRK: {
      symbol: "kn",
      name: "Croatian Kuna",
      symbol_native: "kn",
      decimal_digits: 2,
      rounding: 0,
      code: "HRK",
      name_plural: "Croatian kunas",
    },
    HUF: {
      symbol: "Ft",
      name: "Hungarian Forint",
      symbol_native: "Ft",
      decimal_digits: 0,
      rounding: 0,
      code: "HUF",
      name_plural: "Hungarian forints",
    },
    IDR: {
      symbol: "Rp",
      name: "Indonesian Rupiah",
      symbol_native: "Rp",
      decimal_digits: 0,
      rounding: 0,
      code: "IDR",
      name_plural: "Indonesian rupiahs",
    },
    ILS: {
      symbol: "\u20aa",
      name: "Israeli New Sheqel",
      symbol_native: "\u20aa",
      decimal_digits: 2,
      rounding: 0,
      code: "ILS",
      name_plural: "Israeli new sheqels",
    },
    INR: {
      symbol: "\u20b9",
      name: "Indian Rupee",
      symbol_native: "\u099f\u0995\u09be",
      decimal_digits: 2,
      rounding: 0,
      code: "INR",
      name_plural: "Indian rupees",
    },
    IQD: {
      symbol: "IQD",
      name: "Iraqi Dinar",
      symbol_native: "\u062f.\u0639.\u200f",
      decimal_digits: 0,
      rounding: 0,
      code: "IQD",
      name_plural: "Iraqi dinars",
    },
    IRR: {
      symbol: "IRR",
      name: "Iranian Rial",
      symbol_native: "\ufdfc",
      decimal_digits: 0,
      rounding: 0,
      code: "IRR",
      name_plural: "Iranian rials",
    },
    ISK: {
      symbol: "Ikr",
      name: "Icelandic Kr\xf3na",
      symbol_native: "kr",
      decimal_digits: 0,
      rounding: 0,
      code: "ISK",
      name_plural: "Icelandic kr\xf3nur",
    },
    JMD: {
      symbol: "J$",
      name: "Jamaican Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "JMD",
      name_plural: "Jamaican dollars",
    },
    JOD: {
      symbol: "JD",
      name: "Jordanian Dinar",
      symbol_native: "\u062f.\u0623.\u200f",
      decimal_digits: 3,
      rounding: 0,
      code: "JOD",
      name_plural: "Jordanian dinars",
    },
    JPY: {
      symbol: "\xa5",
      name: "Japanese Yen",
      symbol_native: "\uffe5",
      decimal_digits: 0,
      rounding: 0,
      code: "JPY",
      name_plural: "Japanese yen",
    },
    KES: {
      symbol: "Ksh",
      name: "Kenyan Shilling",
      symbol_native: "Ksh",
      decimal_digits: 2,
      rounding: 0,
      code: "KES",
      name_plural: "Kenyan shillings",
    },
    KHR: {
      symbol: "KHR",
      name: "Cambodian Riel",
      symbol_native: "\u17db",
      decimal_digits: 2,
      rounding: 0,
      code: "KHR",
      name_plural: "Cambodian riels",
    },
    KMF: {
      symbol: "CF",
      name: "Comorian Franc",
      symbol_native: "FC",
      decimal_digits: 0,
      rounding: 0,
      code: "KMF",
      name_plural: "Comorian francs",
    },
    KRW: {
      symbol: "\u20a9",
      name: "South Korean Won",
      symbol_native: "\u20a9",
      decimal_digits: 0,
      rounding: 0,
      code: "KRW",
      name_plural: "South Korean won",
    },
    KWD: {
      symbol: "KD",
      name: "Kuwaiti Dinar",
      symbol_native: "\u062f.\u0643.\u200f",
      decimal_digits: 3,
      rounding: 0,
      code: "KWD",
      name_plural: "Kuwaiti dinars",
    },
    KZT: {
      symbol: "KZT",
      name: "Kazakhstani Tenge",
      symbol_native: "\u0442\u04a3\u0433.",
      decimal_digits: 2,
      rounding: 0,
      code: "KZT",
      name_plural: "Kazakhstani tenges",
    },
    LBP: {
      symbol: "LB\xa3",
      name: "Lebanese Pound",
      symbol_native: "\u0644.\u0644.\u200f",
      decimal_digits: 0,
      rounding: 0,
      code: "LBP",
      name_plural: "Lebanese pounds",
    },
    LKR: {
      symbol: "SLRs",
      name: "Sri Lankan Rupee",
      symbol_native: "SL Re",
      decimal_digits: 2,
      rounding: 0,
      code: "LKR",
      name_plural: "Sri Lankan rupees",
    },
    LTL: {
      symbol: "Lt",
      name: "Lithuanian Litas",
      symbol_native: "Lt",
      decimal_digits: 2,
      rounding: 0,
      code: "LTL",
      name_plural: "Lithuanian litai",
    },
    LVL: {
      symbol: "Ls",
      name: "Latvian Lats",
      symbol_native: "Ls",
      decimal_digits: 2,
      rounding: 0,
      code: "LVL",
      name_plural: "Latvian lati",
    },
    LYD: {
      symbol: "LD",
      name: "Libyan Dinar",
      symbol_native: "\u062f.\u0644.\u200f",
      decimal_digits: 3,
      rounding: 0,
      code: "LYD",
      name_plural: "Libyan dinars",
    },
    MAD: {
      symbol: "MAD",
      name: "Moroccan Dirham",
      symbol_native: "\u062f.\u0645.\u200f",
      decimal_digits: 2,
      rounding: 0,
      code: "MAD",
      name_plural: "Moroccan dirhams",
    },
    MDL: {
      symbol: "MDL",
      name: "Moldovan Leu",
      symbol_native: "MDL",
      decimal_digits: 2,
      rounding: 0,
      code: "MDL",
      name_plural: "Moldovan lei",
    },
    MGA: {
      symbol: "MGA",
      name: "Malagasy Ariary",
      symbol_native: "MGA",
      decimal_digits: 0,
      rounding: 0,
      code: "MGA",
      name_plural: "Malagasy Ariaries",
    },
    MKD: {
      symbol: "MKD",
      name: "Macedonian Denar",
      symbol_native: "MKD",
      decimal_digits: 2,
      rounding: 0,
      code: "MKD",
      name_plural: "Macedonian denari",
    },
    MMK: {
      symbol: "MMK",
      name: "Myanma Kyat",
      symbol_native: "K",
      decimal_digits: 0,
      rounding: 0,
      code: "MMK",
      name_plural: "Myanma kyats",
    },
    MOP: {
      symbol: "MOP$",
      name: "Macanese Pataca",
      symbol_native: "MOP$",
      decimal_digits: 2,
      rounding: 0,
      code: "MOP",
      name_plural: "Macanese patacas",
    },
    MUR: {
      symbol: "MURs",
      name: "Mauritian Rupee",
      symbol_native: "MURs",
      decimal_digits: 0,
      rounding: 0,
      code: "MUR",
      name_plural: "Mauritian rupees",
    },
    MXN: {
      symbol: "MX$",
      name: "Mexican Peso",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "MXN",
      name_plural: "Mexican pesos",
    },
    MYR: {
      symbol: "RM",
      name: "Malaysian Ringgit",
      symbol_native: "RM",
      decimal_digits: 2,
      rounding: 0,
      code: "MYR",
      name_plural: "Malaysian ringgits",
    },
    MZN: {
      symbol: "MTn",
      name: "Mozambican Metical",
      symbol_native: "MTn",
      decimal_digits: 2,
      rounding: 0,
      code: "MZN",
      name_plural: "Mozambican meticals",
    },
    NAD: {
      symbol: "N$",
      name: "Namibian Dollar",
      symbol_native: "N$",
      decimal_digits: 2,
      rounding: 0,
      code: "NAD",
      name_plural: "Namibian dollars",
    },
    NGN: {
      symbol: "\u20a6",
      name: "Nigerian Naira",
      symbol_native: "\u20a6",
      decimal_digits: 2,
      rounding: 0,
      code: "NGN",
      name_plural: "Nigerian nairas",
    },
    NIO: {
      symbol: "C$",
      name: "Nicaraguan C\xf3rdoba",
      symbol_native: "C$",
      decimal_digits: 2,
      rounding: 0,
      code: "NIO",
      name_plural: "Nicaraguan c\xf3rdobas",
    },
    NOK: {
      symbol: "Nkr",
      name: "Norwegian Krone",
      symbol_native: "kr",
      decimal_digits: 2,
      rounding: 0,
      code: "NOK",
      name_plural: "Norwegian kroner",
    },
    NPR: {
      symbol: "NPRs",
      name: "Nepalese Rupee",
      symbol_native: "\u0928\u0947\u0930\u0942",
      decimal_digits: 2,
      rounding: 0,
      code: "NPR",
      name_plural: "Nepalese rupees",
    },
    NZD: {
      symbol: "NZ$",
      name: "New Zealand Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "NZD",
      name_plural: "New Zealand dollars",
    },
    OMR: {
      symbol: "OMR",
      name: "Omani Rial",
      symbol_native: "\u0631.\u0639.\u200f",
      decimal_digits: 3,
      rounding: 0,
      code: "OMR",
      name_plural: "Omani rials",
    },
    PAB: {
      symbol: "B/.",
      name: "Panamanian Balboa",
      symbol_native: "B/.",
      decimal_digits: 2,
      rounding: 0,
      code: "PAB",
      name_plural: "Panamanian balboas",
    },
    PEN: {
      symbol: "S/.",
      name: "Peruvian Nuevo Sol",
      symbol_native: "S/.",
      decimal_digits: 2,
      rounding: 0,
      code: "PEN",
      name_plural: "Peruvian nuevos soles",
    },
    PHP: {
      symbol: "\u20b1",
      name: "Philippine Peso",
      symbol_native: "\u20b1",
      decimal_digits: 2,
      rounding: 0,
      code: "PHP",
      name_plural: "Philippine pesos",
    },
    PKR: {
      symbol: "PKRs",
      name: "Pakistani Rupee",
      symbol_native: "\u20a8",
      decimal_digits: 0,
      rounding: 0,
      code: "PKR",
      name_plural: "Pakistani rupees",
    },
    PLN: {
      symbol: "z\u0142",
      name: "Polish Zloty",
      symbol_native: "z\u0142",
      decimal_digits: 2,
      rounding: 0,
      code: "PLN",
      name_plural: "Polish zlotys",
    },
    PYG: {
      symbol: "\u20b2",
      name: "Paraguayan Guarani",
      symbol_native: "\u20b2",
      decimal_digits: 0,
      rounding: 0,
      code: "PYG",
      name_plural: "Paraguayan guaranis",
    },
    QAR: {
      symbol: "QR",
      name: "Qatari Rial",
      symbol_native: "\u0631.\u0642.\u200f",
      decimal_digits: 2,
      rounding: 0,
      code: "QAR",
      name_plural: "Qatari rials",
    },
    RON: {
      symbol: "RON",
      name: "Romanian Leu",
      symbol_native: "RON",
      decimal_digits: 2,
      rounding: 0,
      code: "RON",
      name_plural: "Romanian lei",
    },
    RSD: {
      symbol: "din.",
      name: "Serbian Dinar",
      symbol_native: "\u0434\u0438\u043d.",
      decimal_digits: 0,
      rounding: 0,
      code: "RSD",
      name_plural: "Serbian dinars",
    },
    RUB: {
      symbol: "RUB",
      name: "Russian Ruble",
      symbol_native: "\u0440\u0443\u0431.",
      decimal_digits: 2,
      rounding: 0,
      code: "RUB",
      name_plural: "Russian rubles",
    },
    RWF: {
      symbol: "RWF",
      name: "Rwandan Franc",
      symbol_native: "FR",
      decimal_digits: 0,
      rounding: 0,
      code: "RWF",
      name_plural: "Rwandan francs",
    },
    SAR: {
      symbol: "SR",
      name: "Saudi Riyal",
      symbol_native: "\u0631.\u0633.\u200f",
      decimal_digits: 2,
      rounding: 0,
      code: "SAR",
      name_plural: "Saudi riyals",
    },
    SDG: {
      symbol: "SDG",
      name: "Sudanese Pound",
      symbol_native: "SDG",
      decimal_digits: 2,
      rounding: 0,
      code: "SDG",
      name_plural: "Sudanese pounds",
    },
    SEK: {
      symbol: "Skr",
      name: "Swedish Krona",
      symbol_native: "kr",
      decimal_digits: 2,
      rounding: 0,
      code: "SEK",
      name_plural: "Swedish kronor",
    },
    SGD: {
      symbol: "S$",
      name: "Singapore Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "SGD",
      name_plural: "Singapore dollars",
    },
    SOS: {
      symbol: "Ssh",
      name: "Somali Shilling",
      symbol_native: "Ssh",
      decimal_digits: 0,
      rounding: 0,
      code: "SOS",
      name_plural: "Somali shillings",
    },
    SYP: {
      symbol: "SY\xa3",
      name: "Syrian Pound",
      symbol_native: "\u0644.\u0633.\u200f",
      decimal_digits: 0,
      rounding: 0,
      code: "SYP",
      name_plural: "Syrian pounds",
    },
    THB: {
      symbol: "\u0e3f",
      name: "Thai Baht",
      symbol_native: "\u0e3f",
      decimal_digits: 2,
      rounding: 0,
      code: "THB",
      name_plural: "Thai baht",
    },
    TND: {
      symbol: "DT",
      name: "Tunisian Dinar",
      symbol_native: "\u062f.\u062a.\u200f",
      decimal_digits: 3,
      rounding: 0,
      code: "TND",
      name_plural: "Tunisian dinars",
    },
    TOP: {
      symbol: "T$",
      name: "Tongan Pa\u02bbanga",
      symbol_native: "T$",
      decimal_digits: 2,
      rounding: 0,
      code: "TOP",
      name_plural: "Tongan pa\u02bbanga",
    },
    TRY: {
      symbol: "TL",
      name: "Turkish Lira",
      symbol_native: "TL",
      decimal_digits: 2,
      rounding: 0,
      code: "TRY",
      name_plural: "Turkish Lira",
    },
    TTD: {
      symbol: "TT$",
      name: "Trinidad and Tobago Dollar",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "TTD",
      name_plural: "Trinidad and Tobago dollars",
    },
    TWD: {
      symbol: "NT$",
      name: "New Taiwan Dollar",
      symbol_native: "NT$",
      decimal_digits: 2,
      rounding: 0,
      code: "TWD",
      name_plural: "New Taiwan dollars",
    },
    TZS: {
      symbol: "TSh",
      name: "Tanzanian Shilling",
      symbol_native: "TSh",
      decimal_digits: 0,
      rounding: 0,
      code: "TZS",
      name_plural: "Tanzanian shillings",
    },
    UAH: {
      symbol: "\u20b4",
      name: "Ukrainian Hryvnia",
      symbol_native: "\u20b4",
      decimal_digits: 2,
      rounding: 0,
      code: "UAH",
      name_plural: "Ukrainian hryvnias",
    },
    UGX: {
      symbol: "USh",
      name: "Ugandan Shilling",
      symbol_native: "USh",
      decimal_digits: 0,
      rounding: 0,
      code: "UGX",
      name_plural: "Ugandan shillings",
    },
    UYU: {
      symbol: "$U",
      name: "Uruguayan Peso",
      symbol_native: "$",
      decimal_digits: 2,
      rounding: 0,
      code: "UYU",
      name_plural: "Uruguayan pesos",
    },
    UZS: {
      symbol: "UZS",
      name: "Uzbekistan Som",
      symbol_native: "UZS",
      decimal_digits: 0,
      rounding: 0,
      code: "UZS",
      name_plural: "Uzbekistan som",
    },
    VEF: {
      symbol: "Bs.F.",
      name: "Venezuelan Bol\xedvar",
      symbol_native: "Bs.F.",
      decimal_digits: 2,
      rounding: 0,
      code: "VEF",
      name_plural: "Venezuelan bol\xedvars",
    },
    VND: {
      symbol: "\u20ab",
      name: "Vietnamese Dong",
      symbol_native: "\u20ab",
      decimal_digits: 0,
      rounding: 0,
      code: "VND",
      name_plural: "Vietnamese dong",
    },
    XAF: {
      symbol: "FCFA",
      name: "CFA Franc BEAC",
      symbol_native: "FCFA",
      decimal_digits: 0,
      rounding: 0,
      code: "XAF",
      name_plural: "CFA francs BEAC",
    },
    XOF: {
      symbol: "CFA",
      name: "CFA Franc BCEAO",
      symbol_native: "CFA",
      decimal_digits: 0,
      rounding: 0,
      code: "XOF",
      name_plural: "CFA francs BCEAO",
    },
    YER: {
      symbol: "YR",
      name: "Yemeni Rial",
      symbol_native: "\u0631.\u064a.\u200f",
      decimal_digits: 0,
      rounding: 0,
      code: "YER",
      name_plural: "Yemeni rials",
    },
    ZAR: {
      symbol: "R",
      name: "South African Rand",
      symbol_native: "R",
      decimal_digits: 2,
      rounding: 0,
      code: "ZAR",
      name_plural: "South African rand",
    },
    ZMK: {
      symbol: "ZK",
      name: "Zambian Kwacha",
      symbol_native: "ZK",
      decimal_digits: 0,
      rounding: 0,
      code: "ZMK",
      name_plural: "Zambian kwachas",
    },
  },
};

// FileUpload Constants
export const fileUploadConstants = {
  DEFAULT_CLASSES: {
    DEFAULT_CAPTIONS: {
      MULTIPLE_SELECT: "Drop your files here.",
      SELECT: "Upload",
    },
    DEVICE_CONTENTTYPES: {
      IMAGE: "image",
      VIDEO: "video",
      AUDIO: "audio",
      FILES: "files",
    },
  },
  DEFAULT_VALUES: {
    FILESIZE_MB: 1048576,
    TAB_INDEX: 0,
    MULTIPLE: false,
    FILEUPLOAD_MESSAGE: "You can also browse for files",
    SHOW: true,
    ENABLED: true,
    ICON_CLASS: "wm-sl-l sl-cloud-upload",
    CLEAR_ICON_CLASS: "",
    CLEAR_ICON_HINT: "Clear",
    DELETE_ICON_HINT: "Delete",
    SELECT: "Upload",
    WIDTH: "auto",
    SHOW_PROGRESS_BAR: true,
    SHOW_PROGRESS_BAR_PERCENTAGE: true,
  },
} as const;

// Helper function for getFileIconClass to reference getFileExtension
const getFileExtension = (fileName: string) => {
  if (fileName && includes(fileName, ".")) {
    return toLower(fileName.substring(fileName.lastIndexOf(".") + 1));
  }
  return "";
};

// Export utility functions individually
export const isImageFile = (filename: string) => {
  const ext = filename.split(".").pop()?.toLowerCase();
  return [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "svg",
    "webp",
    "bmp",
    "ico",
    "jpe",
    "tif",
    "tiff",
    "pbm",
  ].includes(ext || "");
};

export const isAudioFile = (filename: string) => {
  const ext = filename.split(".").pop()?.toLowerCase();
  return ["mp3", "wav", "ogg", "aac", "m4a", "wma"].includes(ext || "");
};

export const isVideoFile = (filename: string) => {
  const ext = filename.split(".").pop()?.toLowerCase();
  return ["mp4", "webm", "mov", "avi", "wmv", "flv", "3gp", "mpeg", "mpg"].includes(ext || "");
};

export const isDocumentFile = (filename: string) => {
  const ext = filename.split(".").pop()?.toLowerCase();
  return ["pdf", "doc", "docx", "rtf", "txt", "xls", "xlsx"].includes(ext || "");
};

export const isArchiveFile = (filename: string) => {
  const ext = filename.split(".").pop()?.toLowerCase();
  return ["zip", "rar"].includes(ext || "");
};

export const isDataFile = (filename: string) => {
  const ext = filename.split(".").pop()?.toLowerCase();
  return ["csv", "json", "xml", "js", "log"].includes(ext || "");
};

export { getFileExtension };

export const getFileIconClass = (fileName: string | undefined) => {
  const extension = getFileExtension(fileName || "jpg");

  if (["zip", "rar", "7z"].includes(extension)) {
    return "fa fa-file-zip-o";
  }
  if (["pdf"].includes(extension)) {
    return "fa fa-file-pdf-o";
  }
  if (["mp4", "mov", "avi", "wmv"].includes(extension)) {
    return "fa fa-file-movie-o";
  }
  if (["jpg", "jpeg", "png", "gif", "bmp"].includes(extension)) {
    return "fa fa-file-image-o";
  }
  if (["html", "htm", "js", "css", "scss", "ts", "tsx"].includes(extension)) {
    return "fa fa-file-code-o";
  }
  if (["txt"].includes(extension)) {
    return "fa fa-file-text-o";
  }
  if (["mp3", "wav", "ogg"].includes(extension)) {
    return "fa fa-file-audio-o";
  }

  return "fa fa-file-o"; // Default icon
};

export const DEFAULT_CHIPS_DATASET = ["Option 1", "Option 2", "Option 3"];
