// Animation names
export const iconClassNames = [
    //Wavicon
    "wi wi-dashboard",
    "wi wi-audiotrack",
    "wi wi-battery-empty",
    "wi wi-calendar",
    "wi wi-bar-chart",
    "wi wi-person",
    "wi wi-smartphone",
    "wi wi-photo-camera",
    "wi wi-picture",
    "wi wi-arrow-forward",
    "wi wi-location-arrow",
    "wi wi-menu",
    "wi wi-database",
    "wi wi-file-text",
    "wi wi-location-pin",
    "wi wi-warning",
    "wi wi-check-box",
    "wi wi-error",
    "wi wi-info",
    "wi wi-trash",
    "wi wi-delete",
    "wi wi-sign-in",
    "wi wi-sign-out",


    //FontAwesome
    "fa fa-adjust", 
    "fa fa-anchor", 
    "fa fa-archive", 
    "fa fa-area-chart", 
    "fa fa-asterisk", 
    "fa fa-at", 
    "fa fa-automobile", 
    "fa fa-balance-scale", 
    "fa fa-bank", 
    "fa fa-bar-chart", 
    "fa fa-user",
    "fa fa-warning",
    "fa fa-check-circle",
    "fa fa-trash",
    "fa fa-save",
    "fa fa-file",
]